"""empty message

Revision ID: 52ee7eb6d384
Revises: 51f2b87dcfa4
Create Date: 2022-08-27 09:49:44.618696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ee7eb6d384'
down_revision = '51f2b87dcfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_deal', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_deal', 'status')
    # ### end Alembic commands ###
