"""empty message

Revision ID: ac8d46fc4425
Revises: a9265f39f6aa
Create Date: 2022-08-24 16:32:51.253686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac8d46fc4425'
down_revision = 'a9265f39f6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trabajadores', 'job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trabajadores', sa.Column('job', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
