"""empty message

Revision ID: bc673b81e30c
Revises: ac8d46fc4425
Create Date: 2022-08-24 16:52:27.566846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc673b81e30c'
down_revision = 'ac8d46fc4425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_userName_key', 'user', type_='unique')
    op.drop_column('user', 'userName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userName', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.create_unique_constraint('user_userName_key', 'user', ['userName'])
    # ### end Alembic commands ###
