"""empty message

Revision ID: fbc12eea0f45
Revises: bc673b81e30c
Create Date: 2022-08-27 09:25:24.592508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbc12eea0f45'
down_revision = 'bc673b81e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('controller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajadores_id', sa.Integer(), nullable=True),
    sa.Column('contratante_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contratante_id'], ['contratantes.id'], ),
    sa.ForeignKeyConstraint(['trabajadores_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('controller')
    # ### end Alembic commands ###
